# Generated by Django 4.2.7 on 2023-12-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_request_payment_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method_card',
            field=models.CharField(choices=[('Bank Card', 'Bank Card'), ('pay made ', 'Pay Made ')], default='Cultural', max_length=70),
        ),
    ]
