# Generated by Django 4.2.7 on 2023-12-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_requestcomment_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestcomment',
            name='parent_comment',
        ),
    ]
