# Generated by Django 4.2.7 on 2023-12-27 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_remove_requestcomment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcomment',
            name='requests',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='request.request'),
            preserve_default=False,
        ),
    ]
