# Generated by Django 4.2.7 on 2023-12-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_requestcomment_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestcomment',
            name='service',
        ),
    ]
