# Generated by Django 5.0 on 2023-12-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_typeservice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeservice',
            name='image',
            field=models.ImageField(default='image/default_TypeService.jpeg', upload_to='image/'),
        ),
    ]
